import SwiftUI

public struct LocalizationService: Sendable {
    public static let shared = LocalizationService()
    
    private init() {}
    
    private var isVietnamese: Bool {
        guard let preferredLanguage = Locale.preferredLanguages.first else { return false }
        return preferredLanguage.hasPrefix("vi")
    }
    
    private let dictionary: [String: (en: String, vi: String)] = [
        "tab_home": ("Home", "Trang chủ"),
        "tab_stack": ("Stack", "Danh sách"),
        "tab_history": ("History", "Lịch sử"),
        "tab_settings": ("Settings", "Cài đặt"),
        "dashboard_title": ("Dashboard", "Tổng quan"),
        "history_title": ("History", "Lịch sử"),
        "intake_frequency_last_7": ("Intake Frequency (Last 7 days)", "Tần suất uống (7 ngày qua)"),
        "insights_title": ("Insights", "Gợi ý (7/30 ngày)"),
        "insights_last_7": ("Last 7 days", "7 ngày"),
        "insights_last_30": ("Last 30 days", "30 ngày"),
        "insights_no_data": ("Not enough data.", "Chưa đủ dữ liệu."),
        "insights_total_title": ("TOTAL INTAKES", "TỔNG LƯỢT UỐNG"),
        "insights_completion_chip_format": ("%d%% completion", "%d%% hoàn thành"),
        "insights_late_chip_format": ("%d late", "%d trễ"),
        "insights_details_title": ("Insights details", "Chi tiết gợi ý"),
        "insights_details_top_late_title": ("Top late", "Hay trễ"),
        "insights_details_top_late_hour_title": ("Late hour", "Giờ hay trễ"),
        "insights_details_top_skipped_title": ("Top skipped", "Hay bỏ qua"),
        "insights_completion_format": ("Completion: %d%%", "Hoàn thành: %d%%"),
        "insights_late_format": ("Late: %d", "Trễ: %d"),
        "insights_top_late_hour_format": ("Late hour: %1$@ (%2$d)", "Giờ hay trễ: %1$@ (%2$d)"),
        "insights_top_skipped_format": ("Top skipped: %1$@ (%2$d)", "Hay bỏ qua: %1$@ (%2$d)"),
        "insights_top_late_format": ("Top late: %1$@ (%2$d)", "Hay trễ: %1$@ (%2$d)"),
        "insights_item_bullet_format": ("• %1$@ (%2$d)", "• %1$@ (%2$d)"),
        "log_details": ("Log Details", "Chi tiết nhật ký"),
        "no_logs_yet": ("No logs yet.", "Chưa có nhật ký nào."),
        "today_intake_title": ("Today's Intake", "Cần uống hôm nay"),
        "no_intake_today": ("No intake scheduled for today.", "Không có lịch uống hôm nay."),
        "home_no_overdue": ("No overdue items.", "Không có mốc nào quá hạn."),
        "add_client_to_start": ("Add a Client to start.", "Thêm một học viên để bắt đầu."),
        "Add a Client to start.": ("Add a Client to start.", "Thêm một học viên để bắt đầu."),
        "resting_title": ("Resting", "Đang nghỉ"),
        "taken": ("Taken", "Đã uống"),
        "settings_title": ("Settings", "Cài đặt"),
        "plan_access_title": ("Plan & Access", "Gói & Quyền truy cập"),
        "plan_access_manage": ("Manage plan and access", "Quản lý gói và quyền truy cập"),
        "plan_access_current_plan": ("Current plan", "Gói hiện tại"),
        "plan_access_current_badge": ("Current", "Hiện tại"),
        "plan_access_store_note_ios": ("Purchases and localized prices will be provided by StoreKit in the store-connection stage.", "Mua gói và giá bản địa hóa sẽ được cung cấp bởi StoreKit ở giai đoạn kết nối cửa hàng."),
        "plan_preview_title": ("Plan preview", "Xem trước gói"),
        "plan_preview_body": ("Purchases are not enabled in this build yet. You can compare plans now; paid access stays locked until a store connection is configured.", "Bản dựng này chưa bật mua gói. Bạn vẫn có thể so sánh các gói; quyền trả phí tiếp tục bị khóa cho đến khi kết nối cửa hàng được cấu hình."),
        "plan_free_title": ("Free", "Free"),
        "plan_free_subtitle": ("Core tracking for one person.", "Theo dõi cốt lõi cho một người."),
        "plan_pro_title": ("Pro", "Pro"),
        "plan_pro_subtitle": ("Advanced cycles, analytics and secure sync.", "Chu kỳ nâng cao, phân tích và đồng bộ bảo mật."),
        "plan_coach_title": ("Coach", "Coach"),
        "plan_coach_subtitle": ("Multi-client workflows for coaches.", "Quy trình đa học viên dành cho huấn luyện viên."),
        "plan_feature_basic_tracking": ("Basic supplement tracking", "Theo dõi thực phẩm bổ sung cơ bản"),
        "plan_feature_reminders": ("Reminder notifications", "Thông báo nhắc lịch"),
        "plan_feature_recent_history": ("Recent history", "Lịch sử gần đây"),
        "plan_feature_advanced_cycles": ("Advanced cycle scheduling", "Lịch chu kỳ nâng cao"),
        "plan_feature_unlimited_history": ("Extended history (up to 90 days)", "Lịch sử mở rộng (tối đa 90 ngày)"),
        "plan_feature_adherence_analytics": ("Adherence analytics", "Phân tích mức độ tuân thủ"),
        "plan_feature_encrypted_sync": ("Encrypted cloud sync", "Đồng bộ đám mây có mã hóa"),
        "plan_feature_data_export": ("Data export", "Xuất dữ liệu"),
        "plan_feature_all_pro": ("Everything in Pro", "Toàn bộ tính năng Pro"),
        "plan_feature_multi_client": ("Multi-client management", "Quản lý nhiều học viên"),
        "plan_feature_coach_reports": ("Coach reports", "Báo cáo cho huấn luyện viên"),
        "coach_overview_title": ("Coach Overview", "Tổng quan huấn luyện viên"),
        "coach_overview_open": ("Open", "Mở"),
        "coach_overview_locked_title": ("Coach feature", "Tính năng huấn luyện viên"),
        "coach_overview_locked_body": ("Coach Overview is available with the Coach entitlement. Plan comparison remains available while store connection is deferred.", "Tổng quan huấn luyện viên cần quyền Coach. Bạn vẫn có thể xem so sánh gói trong thời gian chưa kết nối cửa hàng."),
        "coach_overview_last_7_days": ("Last 7 days", "7 ngày gần nhất"),
        "coach_overview_empty": ("No clients yet. Add clients to build a coach overview.", "Chưa có học viên. Hãy thêm học viên để tạo tổng quan huấn luyện viên."),
        "coach_metric_clients": ("Clients", "Học viên"),
        "coach_metric_active": ("Active", "Có hoạt động"),
        "coach_metric_check_in": ("Check-in", "Cần hỏi lại"),
        "coach_check_in_badge": ("Check in", "Cần hỏi lại"),
        "coach_no_recent_records": ("No recent records", "Chưa có ghi nhận gần đây"),
        "coach_completion_format": ("%d%% completion • %d taken • %d skipped", "Hoàn thành %d%% • Đã uống %d • Bỏ qua %d"),
        "coach_last_activity_none": ("No activity in the last 7 days", "Không có hoạt động trong 7 ngày qua"),
        "coach_last_activity_format": ("Last activity: %@", "Hoạt động gần nhất: %@"),
        "billing_store_products": ("Subscriptions", "Gói đăng ký"),
        "billing_buy": ("Buy", "Mua"),
        "billing_restore": ("Restore Purchases", "Khôi phục giao dịch"),
        "billing_purchase_completed": ("Purchase completed. Access updated.", "Mua gói thành công. Quyền truy cập đã cập nhật."),
        "billing_purchase_pending": ("Purchase is pending. Access will unlock after payment completes.", "Giao dịch đang chờ. Quyền truy cập sẽ mở sau khi thanh toán hoàn tất."),
        "billing_purchase_cancelled": ("Purchase cancelled.", "Đã hủy giao dịch."),
        "billing_restore_completed": ("Purchases restored.", "Đã khôi phục giao dịch."),
        "billing_verification_failed": ("Purchase verification failed. Paid access was not granted.", "Xác minh giao dịch thất bại. Quyền trả phí chưa được cấp."),
        "billing_store_unavailable": ("The App Store is unavailable or products are not configured yet.", "App Store đang không khả dụng hoặc sản phẩm chưa được cấu hình."),
        "billing_store_authoritative_note": ("Prices and subscription access are provided by the App Store. OAK Healthy does not unlock paid plans from local settings.", "Giá và quyền đăng ký do App Store cung cấp. OAK Healthy không mở gói trả phí bằng cài đặt cục bộ."),
        "plan_unlock_analytics": ("Unlock adherence analytics with Pro", "Mở phân tích tuân thủ với Pro"),
        "plan_unlock_export": ("Unlock data export with Pro", "Mở xuất dữ liệu với Pro"),
        "plan_unlock_cloud_sync": ("Unlock encrypted cloud sync with Pro", "Mở đồng bộ đám mây có mã hóa với Pro"),
        "plan_advanced_cycles_required": ("Advanced cycle scheduling requires Pro or Coach.", "Lịch chu kỳ nâng cao cần gói Pro hoặc Coach."),
        "plan_client_limit_reached": ("Your current plan allows one client. Upgrade to Coach for multi-client access.", "Gói hiện tại chỉ cho phép một học viên. Nâng cấp Coach để quản lý nhiều học viên."),
        "privacy_diagnostics_title": ("Privacy & Diagnostics", "Quyền riêng tư & Chẩn đoán"),
        "diagnostics_opt_in_title": ("Share anonymous diagnostics", "Chia sẻ chẩn đoán ẩn danh"),
        "diagnostics_opt_in_body": ("Off by default. When enabled, OAK Healthy sends app usage events and crash diagnostics without client IDs, supplement names, doses, intake history, sync codes, keys, file paths, or raw server responses.", "Mặc định tắt. Khi bật, OAK Healthy gửi sự kiện sử dụng ứng dụng và chẩn đoán sự cố nhưng không gửi ID học viên, tên thực phẩm bổ sung, liều dùng, lịch sử uống, mã đồng bộ, khóa, đường dẫn tệp hoặc phản hồi máy chủ thô."),
        "health_disclaimer_body": ("OAK Healthy is a wellness and routine-tracking tool. It does not diagnose, treat, cure, or prevent disease and is not a substitute for professional medical advice.", "OAK Healthy là công cụ theo dõi thói quen và sức khỏe tổng quát. Ứng dụng không chẩn đoán, điều trị, chữa hoặc phòng bệnh và không thay thế tư vấn y tế chuyên môn."),
        "client_management": ("Client Management", "Quản lý học viên"),
        "add_client": ("Add a Client", "Thêm học viên mới"),
        "edit_client": ("Edit Client", "Sửa học viên"),
        "add_supplement_title": ("Add Supplement", "Thêm chất mới"),
        "add_supplement": ("Add supplement", "Thêm chất"),
        "edit_supplement_title": ("Edit Supplement", "Chỉnh sửa"),
        "basic_info_title": ("Basic Info", "Thông tin cơ bản"),
        "schedule_cycle_title": ("Schedule & Cycle", "Lịch trình & Chu kỳ"),
        "add_supplement_intro": ("Build a clear schedule in three quick sections.", "Thiết lập lịch dùng rõ ràng trong ba phần ngắn."),
        "supplement_details_title": ("Supplement", "Chất bổ sung"),
        "supplement_details_body": ("Name it and add the daily dose.", "Nhập tên và liều dùng hàng ngày."),
        "supplement_timing_title": ("Timing", "Thời gian"),
        "supplement_timing_body": ("Choose the start date and reminder times.", "Chọn ngày bắt đầu và các giờ nhắc."),
        "supplement_rhythm_title": ("Rhythm", "Nhịp dùng"),
        "supplement_rhythm_body": ("Set a continuous or cycle-based plan.", "Chọn dùng liên tục hoặc theo chu kỳ."),
        "schedule_mode_title": ("Plan", "Kiểu lịch"),
        "schedule_mode_cycle": ("On / Off", "Uống / Nghỉ"),
        "duration_months_label": ("Duration in months (optional)", "Thời hạn theo tháng (không bắt buộc)"),
        "intake_times_empty": ("Add at least one reminder time.", "Thêm ít nhất một giờ nhắc."),
        "name_hint": ("Name (e.g., Vitamin D3)", "Tên chất (VD: Vitamin D3)"),
        "dose_hint": ("Daily dose (e.g., 1000 IU)", "Liều lượng hàng ngày (VD: 1000 IU)"),
        "add_supplement_error_invalid_name": ("Name is required.", "Vui lòng nhập tên."),
        "add_supplement_error_invalid_time": ("Invalid intake time.", "Giờ uống không hợp lệ."),
        "add_supplement_error_invalid_cycle_days": ("Invalid cycle days.", "Ngày uống/nghỉ không hợp lệ."),
        "add_supplement_error_invalid_interval_days": ("Invalid interval days.", "Khoảng cách ngày không hợp lệ."),
        "add_supplement_error_save_failed_format": ("Save failed: %@", "Lưu thất bại: %@"),
        "start_date": ("Start date", "Ngày bắt đầu"),
        "intake_time": ("Intake time", "Giờ uống"),
        "add_time": ("Add time", "Thêm giờ"),
        "notif_action_taken": ("Taken", "Đã uống"),
        "notif_action_skip": ("Skip", "Bỏ qua"),
        "repeat_weekly": ("Repeat by weekdays", "Lặp theo thứ"),
        "repeat_on_weekdays": ("Repeat on", "Lặp vào"),
        "repeat_every": ("Every (weeks)", "Cách mỗi (tuần)"),
        "every_x_weeks_format": ("Every %d week(s)", "Mỗi %d tuần"),
        "repeat_every_n_days": ("Repeat every N days", "Uống cách N ngày"),
        "interval_days_label": ("Interval days (N)", "Số ngày cách (N)"),
        "example_on_days": ("e.g., 14", "Ví dụ: 14"),
        "example_off_days": ("e.g., 7", "Ví dụ: 7"),
        "save": ("Save", "Lưu"),
        "saving": ("Saving…", "Đang lưu…"),
        "cancel": ("Cancel", "Hủy"),
        "delete": ("Delete", "Xóa"),
        "edit": ("Edit", "Chỉnh sửa"),
        "appearance_title": ("Appearance", "Giao diện"),
        "appearance_light": ("Light", "Sáng"),
        "appearance_dark": ("Dark", "Tối"),
        "appearance_system": ("System", "Hệ thống"),
        "my_list_title": ("My List", "Danh sách của tôi"),
        "manage_stack": ("Manage Stack", "Quản lý danh sách"),
        "no_supplements_yet": ("No supplements yet.", "Chưa có thực phẩm bổ sung."),
        "user_guide_title": ("User Guide", "Hướng dẫn sử dụng"),
        "settings_guide_1": ("Create your stack: add supplements and choose a schedule (continuous, On/Off, every N days, weekly). Home shows what’s due today.", "Tạo danh sách: thêm chất và chọn lịch (liên tục, bật/nghỉ, cách N ngày, theo thứ). Trang chủ sẽ hiển thị những mục cần uống hôm nay."),
        "settings_guide_2": ("Multi-device sync: device A chooses encryption before Host creates a Link Code. Device B imports the key when required, pastes the code, then taps Download once.", "Đồng bộ 2 thiết bị: thiết bị A chọn chế độ mã hóa trước khi tạo mã liên kết. Thiết bị B nhập khóa nếu cần, dán mã rồi bấm Tải về một lần."),
        "settings_guide_3": ("Security & keys: keep the sync key private; it is hidden by default and cannot be recovered. To change encryption or replace an exposed key, revoke the old code and host again.", "Bảo mật & khóa: giữ khóa đồng bộ bí mật; khóa được ẩn mặc định và không thể khôi phục. Muốn đổi chế độ hoặc thay khóa đã lộ, hãy thu hồi mã cũ rồi tạo mã mới."),
        "settings_guide_4": ("Notifications: allow reminders, then press and hold or expand a dose notification to use Taken/Skip. Test notifications do not log a dose.", "Thông báo: hãy cho phép nhắc uống, sau đó nhấn giữ hoặc mở rộng thông báo liều để dùng Đã uống/Bỏ qua. Thông báo thử không ghi nhận liều."),
        "settings_guide_5": ("Auto-Sync: opening or returning to the app syncs immediately. Local edits upload after a short debounce; network and OS background limits still apply.", "Tự động đồng bộ: mở hoặc quay lại ứng dụng sẽ đồng bộ ngay. Chỉnh sửa cục bộ được tải lên sau một khoảng chờ ngắn; mạng và giới hạn chạy nền của hệ điều hành vẫn áp dụng."),
        "settings_guide_6": ("Troubleshooting: for sync errors, verify Internet, Link Code, and encryption key first. Use Notification diagnostics for reminder issues.", "Khắc phục: khi đồng bộ lỗi, kiểm tra Internet, mã liên kết và khóa mã hóa trước. Dùng Chẩn đoán thông báo cho lỗi nhắc lịch."),
        "settings_guide_7": ("Status: green = Taken, orange = Skipped, red = Overdue. Use filters to focus on Due/Overdue quickly.", "Trạng thái: xanh = Đã uống, cam = Bỏ qua, đỏ = Quá hạn. Dùng bộ lọc để tập trung nhanh vào Đến hạn/Quá hạn."),
        "about_title": ("About", "Giới thiệu"),
        "settings_about_body": ("OAK Healthy is a wellness routine tracker for individuals and coaches. Plan supplement schedules, reminders and adherence history without medical diagnosis or treatment claims.", "OAK Healthy là ứng dụng theo dõi thói quen sức khỏe dành cho cá nhân và huấn luyện viên. Quản lý lịch thực phẩm bổ sung, nhắc lịch và lịch sử tuân thủ mà không đưa ra chẩn đoán hay tuyên bố điều trị y khoa."),
        "copyright_title": ("Copyright & Author", "Bản quyền & Tác giả"),
        "settings_app_name_label": ("OAK Healthy v1.0.1", "Tên app: OAK Healthy v1.0.1"),
        "settings_author_label": ("Author: Quach Gia (Phong QK)", "Tác giả: Quach Gia (Phong QK)"),
        "settings_copyright_body": ("Copyright © 2026 Quach Gia / OAK Healthy. All rights reserved.", "© 2026 Quach Gia / OAK Healthy. Mọi quyền được bảo lưu."),
        "export_data": ("Export Data", "Xuất dữ liệu"),
        "import_data": ("Import Data", "Nhập dữ liệu"),
        "share_stack": ("Share Stack", "Chia sẻ danh sách"),
        "data_tools": ("Data", "Dữ liệu"),
        "error_title": ("Error", "Lỗi"),
        "ok": ("OK", "OK"),
        "back": ("Back", "Quay lại"),
        "onboarding_title": ("Setup", "Thiết lập"),
        "onboarding_next": ("Next", "Tiếp tục"),
        "onboarding_done": ("Done", "Xong"),
        "onboarding_open_settings": ("Open Settings", "Mở Cài đặt"),
        "onboarding_step_client_title": ("Choose a client", "Chọn học viên"),
        "onboarding_step_client_body": ("Select an existing client or create a new one to start tracking.", "Chọn học viên hiện có hoặc tạo mới để bắt đầu theo dõi."),
        "onboarding_step_notifications_title": ("Enable notifications", "Bật thông báo"),
        "onboarding_step_notifications_body": ("Enable notifications so reminders can work reliably.", "Bật thông báo để nhắc uống hoạt động ổn định."),
        "onboarding_notifications_denied": ("Notifications are denied. Enable them in Settings to receive reminders.", "Bạn đã tắt quyền thông báo. Hãy bật lại trong Cài đặt để nhận nhắc uống."),
        "onboarding_permission_status": ("Permission", "Quyền"),
        "onboarding_permission_granted": ("Granted", "Đã cho phép"),
        "onboarding_permission_denied": ("Denied", "Chưa cho phép"),
        "onboarding_permission_not_determined": ("Not asked", "Chưa hỏi"),
        "onboarding_send_test_notification": ("Send test notification", "Gửi thông báo test"),
        "onboarding_test_notification_body": ("Test notification from OAK Healthy.", "Thông báo test từ OAK Healthy."),
        "onboarding_test_sent_format": ("Sent: %@", "Đã gửi: %@"),
        "onboarding_test_ack_format": ("Opened: %@", "Đã mở: %@"),
        "onboarding_reschedule_now": ("Reschedule now", "Đặt lại lịch ngay"),
        "notification_diagnostics_title": ("Notification diagnostics", "Chẩn đoán thông báo"),
        "settings_clear_pending_notifications": ("Clear pending notifications", "Xoá lịch nhắc (pending)"),
        "onboarding_step_done_title": ("All set", "Hoàn tất"),
        "onboarding_step_done_body": ("Next, add your first supplement and reminder time to create your first useful routine. You can change setup options anytime in Settings.", "Tiếp theo, hãy thêm supplement đầu tiên và giờ nhắc để tạo routine hữu ích đầu tiên. Bạn có thể thay đổi các thiết lập bất cứ lúc nào trong Cài đặt."),
        "import_failed": ("Import failed.", "Nhập dữ liệu thất bại."),
        "export_failed": ("Export failed.", "Xuất dữ liệu thất bại."),
        "invalid_json": ("Invalid JSON file.", "File JSON không hợp lệ."),
        "missing_active_client": ("Please select a client first.", "Vui lòng chọn học viên trước."),
        "client_name_label": ("Name", "Tên"),
        "client_name_hint": ("Client name", "Tên học viên"),
        "client_editor_body": ("Use a short, recognizable name. Each client keeps a separate supplement stack and history.", "Dùng tên ngắn, dễ nhận biết. Mỗi học viên có Stack và lịch sử riêng."),
        "client_create_action": ("Create client", "Tạo học viên"),
        "supplement_advice_vitamin_d3": ("Take with a fat-containing meal for better absorption.", "Uống cùng bữa ăn có chất béo để hấp thụ tốt hơn."),
        "supplement_advice_ashwagandha": ("Supports stress reduction and sleep quality.", "Hỗ trợ giảm stress và cải thiện chất lượng giấc ngủ."),
        "supplement_advice_boron": ("Cycle it to support hormone optimization.", "Nên dùng theo chu kỳ để hỗ trợ tối ưu hormone."),
        "supplement_advice_magnesium": ("Supports muscles and nervous system. Take before sleep.", "Uống 30 phút trước khi đi ngủ."),
        "supplement_advice_caffeine": ("Boosts focus and energy for workouts and trading sessions. Take ~30 minutes pre-workout.", "Tăng tập trung và năng lượng trước khi tập hoặc giao dịch. Uống khoảng 30 phút trước khi tập."),
        "supplement_advice_omega_3": ("Take after a fatty meal for best absorption.", "Nên uống sau bữa ăn có chất béo để hấp thụ tốt nhất."),
        "supplement_advice_coq10": ("Supports cellular energy. Take after a meal.", "Hỗ trợ năng lượng tế bào. Nên uống sau bữa ăn."),
        "supplement_advice_creatine": ("Supports strength and performance. Take daily.", "Hỗ trợ sức mạnh và hiệu suất. Uống mỗi ngày để duy trì."),
        "supplement_advice_zinc": ("Avoid taking on an empty stomach.", "Tránh uống khi bụng đói."),
        "supplement_advice_nac": ("Take near bedtime if it suits you. Avoid taking too late if it disrupts sleep.", "Gợi ý: uống gần giờ đi ngủ (trước khi ngủ khoảng 30–60 phút). Nếu bạn nhạy cảm, tránh uống quá muộn."),
        "update_available_title": ("Update Available", "Có bản cập nhật mới"),
        "update_available_message_format": ("Update to get the latest features and security improvements (v%@).", "Hãy cập nhật để trải nghiệm những tính năng mới nhất và tăng cường bảo mật (v%@)."),
        "update_now": ("Update Now", "Cập nhật ngay"),
        "later": ("Later", "Để sau"),
        "update_description": ("Update Coach Mode, Liquid Glass UI, and data synchronization.", "Cập nhật tính năng Quản lý học viên (Coach Mode), tối ưu giao diện Liquid Glass và đồng bộ dữ liệu."),
        "dedication_text": ("With all dedication and research in the fitness & trading journey.", "Bằng cả tâm huyết và nghiên cứu trong hành trình gym & trading."),
        "factory_reset": ("Factory Reset", "Khôi phục cài đặt gốc"),
        "wipe_data_warning": ("This will permanently delete all clients and logs. Continue?", "Hành động này sẽ xóa toàn bộ dữ liệu học viên và nhật ký. Tiếp tục?"),
        "not_available": ("N/A", "N/A"),
        "dose_format": ("Dose: %@", "Liều lượng: %@"),
        "days_remaining_format": ("%d days left", "Còn %d ngày"),
        "cycle_status_on": ("In cycle", "Đang trong chu kỳ"),
        "cycle_status_off": ("In rest", "Đang trong kỳ nghỉ"),
        "home_filter_hint_format": ("Filtered. %d other items. Tap again to show all.", "Đang lọc. Còn %d mục khác. Chạm lại để xem tất cả."),
        "dose_status_missed": ("Missed", "Quá hạn"),
        "dose_status_skipped": ("Skipped", "Bỏ qua"),
        "dose_status_planned": ("Planned", "Chưa uống"),
        "dose_status_due": ("Due", "Đến hạn"),
        "cycle_until_format": ("Until %@", "Đến %@"),
        "cycle_continuous": ("Continuous", "Uống liên tục"),
        "cycle_summary_format": ("%@, %d on / %d off", "%@, %d ngày uống / %d ngày nghỉ"),
        "cycle_label_day_format": ("Day %d/%d", "Ngày %d/%d"),
        "cycle_label_rest_format": ("Rest %d/%d", "Nghỉ %d/%d"),
        "continuous": ("Continuous", "Uống liên tục"),
        "on_days": ("On Days", "Số ngày uống"),
        "off_days": ("Off Days", "Số ngày nghỉ"),
        "duration": ("Duration", "Tổng thời hạn"),
        "months": ("Days", "Ngày"),
        "unlimited": ("Unlimited", "Vô thời hạn"),
        "suggested_format": ("Suggested: %@", "Gợi ý: %@"),
        "notification_title": ("Time to take it! 🌿", "Đến giờ uống rồi! 🌿"),
        "notification_body_format": ("You need to take %1$@ - Dose: %2$@. Wishing you a productive work/trading session!", "Bạn cần nạp %1$@ - Liều lượng: %2$@. Chúc bạn một phiên giao dịch/làm việc hiệu quả!"),
        "chart_axis_day": ("Day", "Ngày"),
        "chart_axis_count": ("Count", "Số lần"),
        
        "sync_center_title": ("Sync Center", "Sync Center"),
        "sync_center_notice_title": ("Notice", "Thông báo"),
        "sync_center_error_missing_firebase_config": ("This build is missing its Firebase configuration. Please update the app before syncing.", "Bản cài đặt này thiếu cấu hình Firebase. Vui lòng cập nhật app trước khi đồng bộ."),
        "sync_center_auto_sync": ("Auto-Sync", "Tự động đồng bộ"),
        "sync_center_onboarding_header": ("Onboarding", "Onboarding"),
        "sync_center_onboarding_host_1": ("1) Enable encryption for security (recommended).", "1) Bật Mã hoá nếu muốn bảo mật (khuyến nghị)."),
        "sync_center_onboarding_host_2": ("2) Tap Host to create a link code.", "2) Bấm Phát dữ liệu để tạo mã liên kết."),
        "sync_center_onboarding_host_3": ("3) Copy the code to device B (Link tab).", "3) Copy mã và gửi sang thiết bị B (tab Link)."),
        "sync_center_onboarding_link_1": ("1) If Host uses encryption, import its sync key first.", "1) Nếu Host dùng mã hoá, hãy import sync key trước."),
        "sync_center_onboarding_link_2": ("2) Enter the link code and tap Download once.", "2) Nhập mã liên kết rồi bấm Tải về một lần."),
        "sync_center_onboarding_link_3": ("3) Enable Auto-Sync for immediate foreground updates.", "3) Bật Tự động đồng bộ để nhận thay đổi ngay khi app hoạt động."),
        
        "sync_center_status_header": ("Status", "Trạng thái"),
        "sync_center_last_sync_format": ("Last sync: %@", "Lần sync gần nhất: %@"),
        "sync_center_last_attempt_format": ("Last attempt: %@", "Lần thử gần nhất: %@"),
        "sync_center_no_sync_yet": ("No sync yet.", "Chưa có sync lần nào"),
        "sync_center_phase_format": ("Phase: %@", "Trạng thái: %@"),
        "sync_center_chip_pull": ("Pull", "Pull"),
        "sync_center_chip_merge": ("Merge", "Merge"),
        "sync_center_chip_push": ("Push", "Push"),
        "sync_center_pending_changes": ("Local changes pending upload.", "Có thay đổi cục bộ chưa upload"),
        "sync_center_no_pending_changes": ("No local pending changes.", "Không có thay đổi cục bộ"),
        "sync_center_conflict_retry_format": ("Conflict retry: %d/1", "Conflict retry: %d/1"),
        "sync_center_bytes_format": ("Download: %@ • Upload: %@", "Download: %@ • Upload: %@"),
        "sync_center_timings_format": ("Pull %dms • Merge %dms • Push %dms • Total %dms", "Pull %dms • Merge %dms • Push %dms • Total %dms"),
        "sync_center_last_error_format": ("Last error: %@", "Lỗi lần trước: %@"),
        "sync_center_hint_missing_key": ("Hint: missing sync key. Copy the key from Host and import it in Security.", "Gợi ý: có thể thiếu sync key. Hãy copy key từ thiết bị Host và Import key trong mục Bảo mật."),
        "sync_center_sync_now": ("Sync now", "Sync ngay"),
        "sync_center_no_link_code": ("No link code yet. Use Host to create one, or Link to enter a code.", "Chưa có mã liên kết. Vào tab Host để phát, hoặc tab Link để nhập mã."),
        
        "sync_center_tab_host": ("Host", "Host"),
        "sync_center_tab_link": ("Link", "Link"),
        "sync_center_device_header": ("Device", "Thiết bị"),
        
        "sync_center_host_action": ("Host", "Phát dữ liệu"),
        "sync_center_rehost_confirm": ("Re-host? Current code will be revoked and a new one will be created.", "Phát dữ liệu lại? Mã hiện tại sẽ bị thu hồi và tạo mã mới."),
        "sync_center_rehost_confirm_action": ("Create new code", "Tạo mã mới"),
        "sync_center_your_link_code": ("Your link code:", "Mã liên kết của bạn:"),
        "sync_center_revoke_action": ("Revoke code", "Thu hồi mã"),
        "sync_center_revoke_confirm": ("Are you sure you want to revoke the code? Other devices will no longer be able to sync.", "Bạn chắc chắn muốn thu hồi mã? Thiết bị khác sẽ không còn sync được với mã hiện tại."),
        "sync_center_host_hint": ("Create a link code so another device can enter it in the Link tab.", "Tạo mã liên kết để thiết bị khác nhập vào tab Link."),
        
        "sync_center_link_code_placeholder": ("Enter link code", "Nhập mã liên kết"),
        "sync_center_download_action": ("Download", "Tải về"),
        "sync_center_unlink_action": ("Unlink this device", "Bỏ liên kết thiết bị này"),
        
        "sync_center_security_header": ("Security", "Bảo mật"),
        "sync_center_encryption_toggle": ("Cloud encryption", "Mã hoá dữ liệu cloud"),
        "sync_center_disable_encryption_confirm": ("Disable encryption? Data will be uploaded as plaintext JSON.", "Tắt mã hoá? Dữ liệu sẽ upload dạng plaintext JSON."),
        "sync_center_disable_encryption_action": ("Disable encryption", "Tắt mã hoá"),
        "sync_center_keep_encryption_action": ("Keep encryption", "Giữ mã hoá"),
        "sync_center_export_key_label": ("Sync key (copy to other device):", "Sync key (copy sang thiết bị khác):"),
        "sync_center_action_copy_key": ("Copy key", "Copy key"),
        "sync_center_refresh_key_action": ("Refresh key", "Refresh key"),
        "sync_center_import_key_placeholder": ("Enter keyId:base64", "Nhập keyId:base64"),
        "sync_center_import_key_action": ("Import key", "Import key"),
        "sync_center_encryption_locked_hint": ("Encryption follows the active Link Code. Revoke or unlink it before changing this setting.", "Mã hoá đi theo Link Code đang hoạt động. Hãy thu hồi hoặc bỏ liên kết trước khi đổi cài đặt này."),
        "sync_center_encryption_off_hint": ("Cloud data is plaintext. Enable encryption before hosting.", "Dữ liệu cloud đang ở dạng plaintext. Hãy bật mã hoá trước khi Host."),
        
        "sync_center_import_key_confirm_invalid": ("Import key? Format: keyId:base64", "Import key? (format keyId:base64)"),
        "sync_center_import_key_confirm_same_current_format": ("Import key? KeyId matches current key (%@).", "Import key? KeyId trùng current key (%@)."),
        "sync_center_import_key_confirm_same_previous_format": ("Import key? KeyId matches previous key (%@).", "Import key? KeyId trùng previous key (%@)."),
        "sync_center_import_key_confirm_format": ("Import key? KeyId: %@", "Import key? KeyId: %@"),
        
        "sync_center_logs_header": ("Logs", "Log"),
        "sync_center_logs_hint": ("Logs will appear when you host/link and run sync.", "Log sẽ xuất hiện khi bạn host/link và thực hiện sync."),
        "sync_center_logs_search_placeholder": ("Search logs", "Tìm trong log"),
        "sync_center_logs_phase": ("Phase", "Phase"),
        "sync_center_logs_phase_all": ("All", "All"),
        "sync_log_phase_host": ("Host", "Host"),
        "sync_log_phase_sync": ("Sync", "Sync"),
        "sync_log_phase_conflict": ("Conflict", "Conflict"),
        "sync_log_phase_done": ("Done", "Xong"),
        "sync_log_phase_error": ("Error", "Lỗi"),
        "sync_center_logs_export": ("Export log", "Export log"),
        "sync_center_logs_clear": ("Clear log", "Clear log"),
        "sync_center_clear_log_confirm": ("Clear sync logs? This only clears logs on this device.", "Xoá log sync? Hành động này chỉ xoá log trên thiết bị hiện tại."),
        "sync_center_clear_log_action": ("Clear log", "Xoá log"),
        "sync_center_no_logs": ("No logs yet.", "Chưa có log."),
        
        "sync_center_toast_missing_client": ("Missing active client.", "Thiếu client đang chọn."),
        "sync_center_toast_missing_link_code": ("Please enter a link code.", "Vui lòng nhập mã liên kết."),
        "sync_center_toast_invalid_link_code": ("Invalid Link Code.", "Link Code không hợp lệ."),
        "sync_center_toast_host_success": ("Hosted successfully!", "Phát dữ liệu thành công!"),
        "sync_center_toast_host_failed_format": ("Host failed: %@", "Phát dữ liệu thất bại: %@"),
        "sync_center_toast_revoke_done": ("Code revoked.", "Đã vô hiệu hóa mã."),
        "sync_center_toast_revoke_failed_format": ("Revoke failed: %@", "Thu hồi mã thất bại: %@"),
        "sync_center_toast_sync_success": ("Sync completed.", "Đã đồng bộ thành công."),
        "sync_center_toast_sync_failed_format": ("Sync failed: %@", "Sync thất bại: %@"),
        "sync_center_toast_encryption_on": ("Encryption enabled.", "Đã bật mã hoá."),
        "sync_center_toast_encryption_off": ("Encryption disabled.", "Đã tắt mã hoá."),
        "sync_center_toast_encryption_failed_format": ("Encryption failed: %@", "Mã hoá thất bại: %@"),
        "sync_center_toast_import_key_done": ("Key imported.", "Đã import key."),
        "sync_center_toast_import_key_failed_format": ("Import failed: %@", "Import key thất bại: %@"),
        "sync_center_toast_code_copied": ("Copied to clipboard.", "Đã sao chép mã vào clipboard."),
        "sync_center_toast_key_copied": ("Key copied for 2 minutes.", "Đã copy key trong 2 phút."),
        "sync_center_action_paste": ("Paste", "Dán"),
        "sync_center_toast_log_cleared": ("Logs cleared.", "Đã xoá log."),
        "sync_center_stack_id_label_format": ("Stack: %@", "Stack: %@"),
        "sync_center_history_id_label_format": ("History: %@", "History: %@"),
        
        "sync_phase_idle": ("Idle", "Idle"),
        "sync_phase_pulling": ("Pulling", "Đang pull"),
        "sync_phase_merging": ("Merging", "Đang merge"),
        "sync_phase_pushing": ("Pushing", "Đang push"),
        "sync_phase_retrying_conflict": ("Retrying (conflict)", "Đang retry (conflict)"),
        "sync_phase_done": ("Done", "Done"),
        "sync_phase_error": ("Error", "Error"),
        
        "import_notice_title": ("Import Notice", "Thông báo Nhập dữ liệu"),
        "notification_permission_toggle": ("Allow notifications", "Cho phép gửi thông báo"),
        "reliability_last_rebuild": ("Last reminder rebuild", "Lần dựng lại lịch nhắc gần nhất"),
        "reliability_never": ("Never", "Chưa có"),
        "notification_reschedule_now": ("Reschedule notifications now", "Đặt lịch lại thông báo"),
        "notification_clear_pending": ("Clear pending notifications", "Xoá thông báo đang chờ"),
        "settings_notifications_title": ("Notifications", "Thông báo"),
        "notification_pending_format": ("Pending: %d", "Đang chờ: %d"),
        "notification_clear_pending_confirm_title": ("Clear pending notifications?", "Xoá thông báo đang chờ?"),
        "notification_clear_pending_confirm_message": ("This will remove all scheduled reminders on this device. Continue?", "Hành động này sẽ xoá toàn bộ lịch nhắc trên thiết bị này. Tiếp tục?"),
        "notification_debug_title": ("Notification List", "Danh sách thông báo"),
        "notification_debug_link": ("Check notification list", "Kiểm tra danh sách thông báo"),
        "notification_debug_empty": ("No schedules yet. Enable “Allow notifications” to activate.", "Chưa có mốc giờ nào. Vui lòng bật 'Cho phép gửi thông báo' để kích hoạt."),
        "notification_debug_dose_format": ("Dose: %@", "Liều lượng: %@"),
        "notification_debug_source_pending": ("Pending", "Pending"),
        "notification_debug_source_shadow": ("Shadow", "Shadow"),
        "notification_debug_diagnostics_section": ("Diagnostics", "Chẩn đoán"),
        "notification_debug_enabled_user_label": ("Enabled (User)", "Bật (Người dùng)"),
        "notification_debug_active_client_label": ("Active client", "Học viên đang chọn"),
        "notification_debug_active_supplements_label": ("Active supplements", "Số chất đang dùng"),
        "notification_debug_pending_os_label": ("Pending (OS)", "Pending (OS)"),
        "notification_debug_shadow_label": ("Shadow", "Shadow"),
        "notification_debug_pending_only_label": ("Pending only", "Chỉ Pending"),
        "notification_debug_shadow_only_label": ("Shadow only", "Chỉ Shadow"),
        "notification_debug_shadow_errors_label": ("Shadow errors", "Lỗi Shadow"),
        "notification_debug_repair_shadow": ("Repair (Shadow)", "Sửa (Shadow)"),
        
        "notification_debug_diag_denied_title": ("Denied", "Chưa cho phép"),
        "notification_debug_diag_off_title": ("Off", "Đang tắt"),
        "notification_debug_diag_no_active_client_title": ("No active client", "Chưa chọn học viên"),
        "notification_debug_diag_no_supplements_title": ("No supplements", "Chưa có chất nào"),
        "notification_debug_diag_scheduled_zero_title": ("Scheduled = 0", "Chưa có lịch"),
        "notification_debug_diag_mismatch_title": ("Mismatch", "Lệch lịch"),
        "notification_debug_diag_ok_title": ("OK", "OK"),
        
        "notification_debug_diag_denied_hint": ("Permission denied. Enable notifications in Settings.", "Bạn đã từ chối quyền. Vào Cài đặt để bật quyền thông báo."),
        "notification_debug_diag_not_determined_hint": ("Permission not requested yet. Turn ON the toggle to request.", "Chưa xin quyền. Bật công tắc để xin quyền thông báo."),
        "notification_debug_diag_off_hint": ("User toggle is OFF. Turn ON to schedule reminders.", "Công tắc thông báo đang tắt. Bật lên để lên lịch."),
        "notification_debug_diag_no_active_client_hint": ("Select an active client first.", "Hãy chọn học viên trước."),
        "notification_debug_diag_no_supplements_hint": ("Add at least one supplement for the active client.", "Thêm ít nhất 1 chất cho học viên đang chọn."),
        "notification_debug_diag_scheduled_zero_hint": ("No pending requests. Reschedule from Settings if needed.", "Chưa có lịch. Thử 'Đặt lịch lại' ở Cài đặt."),
        "notification_debug_diag_shadow_error_hint": ("Some schedules failed. Check Shadow errors in the list/log.", "Có lịch bị lỗi. Xem 'Shadow errors' để biết chi tiết."),
        "notification_debug_diag_pending_only_hint": ("Pending has entries not found in Shadow. Try Clear pending then Reschedule.", "Pending có mục không có trong Shadow. Thử 'Xoá pending' rồi 'Đặt lịch lại'."),
        "notification_debug_diag_shadow_only_hint": ("Shadow has entries missing in Pending. Reschedule may have failed or been cleared.", "Shadow có mục nhưng Pending không có. Có thể lịch bị xoá hoặc lên lịch thất bại."),
        "notification_debug_diag_ok_hint": ("Healthy state.", "Trạng thái ổn."),
        
        "status_on": ("ON", "BẬT"),
        "status_off": ("OFF", "TẮT"),
        "status_yes": ("YES", "CÓ"),
        "status_no": ("NO", "KHÔNG"),
        "backup_last_export_format": ("Last export: %@", "Xuất lần cuối: %@"),
        "backup_last_import_format": ("Last import: %@", "Nhập lần cuối: %@"),
        "backup_json_placeholder": ("Paste backup JSON here…", "Dán JSON backup vào đây…"),
        "backup_paste_from_clipboard": ("Paste from clipboard", "Dán từ clipboard"),
        "backup_preview_action": ("Preview", "Xem trước"),
        "backup_preview_title": ("Preview", "Xem trước"),
        "backup_preview_schema_label": ("Schema", "Schema"),
        "backup_preview_updated_label": ("Updated", "Cập nhật"),
        "backup_preview_device_label": ("Device", "Thiết bị"),
        "backup_preview_stack_label": ("Stack", "Stack"),
        "backup_preview_history_label": ("History", "Lịch sử"),
        
        "multi_device_sync_header": ("Multi-device Sync", "Đồng bộ đa thiết bị"),
        
        "history_today": ("Today", "Hôm nay"),
        "history_yesterday": ("Yesterday", "Hôm qua"),
        "filter_all": ("All", "Tất cả"),
        "history_search_placeholder": ("Search supplements", "Tìm theo tên chất"),
        
        "home_confirm_intake_title": ("Confirm intake?", "Xác nhận uống?"),
        "home_confirm_intake_action": ("Taken", "Đã uống"),
        "home_confirm_intake_message": ("This action will be recorded in History and cannot be undone.", "Hành động này sẽ được ghi vào Lịch sử và không thể hoàn tác."),
        "home_streak_format": ("Streak: %d", "Chuỗi: %d"),
        "recovery_title": ("Get back on track", "Quay lại nhịp"),
        "recovery_body_format": ("%d overdue item(s). Review them and record Taken or Skip when you are ready.", "Có %d mục quá hạn. Hãy xem lại và ghi Đã uống hoặc Bỏ qua khi phù hợp."),
        "recovery_review_action": ("Review", "Xem lại"),
        "home_due_soon": ("Due soon", "Sắp tới"),
        "home_almost_missed": ("Almost missed", "Sắp trễ"),
        
        "user_guide_section_1_title": ("Section 1: Stack & Schedule", "Mục 1: Stack & Lịch uống"),
        "user_guide_section_2_title": ("Section 2: Sync Center", "Mục 2: Sync Center"),
        "user_guide_section_3_title": ("Section 3: Encryption & Keys", "Mục 3: Mã hoá & Key"),
        "user_guide_section_4_title": ("Section 4: Notifications", "Mục 4: Thông báo"),
        "user_guide_section_5_title": ("Section 5: Auto-Sync", "Mục 5: Auto‑Sync"),
        "user_guide_section_6_title": ("Section 6: Troubleshooting", "Mục 6: Khắc phục"),
        "user_guide_section_7_title": ("Section 7: Status & Filters", "Mục 7: Trạng thái & Lọc"),
        
        "app_name": ("OAK Healthy", "OAK Healthy"),
        "demo_preview_title": ("Synthetic Demo", "Demo dữ liệu giả lập"),
        "demo_preview_body": ("Debug-only preview. All names, routines and results below are synthetic and are never written to your data.", "Chỉ có trong debug build. Toàn bộ tên, lịch và kết quả bên dưới là dữ liệu giả lập và không được ghi vào dữ liệu của bạn."),
        "demo_preview_client": ("Demo Athlete", "Vận động viên Demo"),
        "demo_preview_streak": ("6 day streak", "Chuỗi 6 ngày"),
        "demo_preview_due": ("Due 2", "Đến hạn 2"),
        "demo_preview_overdue": ("Overdue 1", "Quá hạn 1"),
        "demo_preview_taken": ("Taken 3", "Đã uống 3"),
        "preview_unavailable": ("Preview unavailable", "Không thể hiển thị preview"),
        "imported_client_default_name": ("Imported Client", "Học viên đã nhập"),
        
        "safe_mode_title": ("Safe Mode", "Chế độ an toàn"),
        "safe_mode_header": ("Safe Mode", "Chế độ an toàn"),
        "safe_mode_apply_button": ("Apply downloaded data", "Áp dụng dữ liệu đã tải"),
        "safe_mode_discard_button": ("Discard downloaded data", "Hủy dữ liệu đã tải"),
        "safe_mode_auto_sync_toggle": ("Auto-Sync", "Tự động đồng bộ"),
        "safe_mode_exit_button": ("Exit Safe Mode", "Thoát chế độ an toàn"),
        "safe_mode_detected_message": ("Downloaded data detected. Preview it before applying.", "Đã phát hiện dữ liệu tải về. Hãy xem trước trước khi áp dụng."),
        "safe_mode_preview_button": ("Preview downloaded data", "Xem trước dữ liệu tải về"),
        "safe_mode_confirm_apply_button": ("Confirm and apply", "Xác nhận và áp dụng"),
        "safe_mode_preview_format": ("Preview %@: %d supplements, %d history entries. Blocking issues: %d duplicate supplement IDs, %d duplicate history IDs, %d orphan history entries.", "Xem trước %@: %d chất bổ sung, %d bản ghi lịch sử. Lỗi chặn: %d ID chất bổ sung trùng, %d ID lịch sử trùng, %d bản ghi lịch sử mồ côi."),
        "safe_mode_preview_changed": ("The downloaded file changed after preview. Review the updated counts before confirming again.", "Tệp tải về đã thay đổi sau khi xem trước. Hãy kiểm tra lại số liệu trước khi xác nhận."),
        "safe_mode_apply_success_message": ("Data applied. Exit Safe Mode to continue using the app.", "Áp dụng dữ liệu thành công. Hãy thoát chế độ an toàn để sử dụng app."),
        "safe_mode_apply_failed_format": ("Apply failed: %@", "Áp dụng dữ liệu thất bại: %@"),
        
        "integrity_blocked_title": ("Security notice", "Cảnh báo bảo mật"),
        "integrity_blocked_body": ("This device failed integrity checks (root/jailbreak/debug). For your safety, the app is disabled.", "Thiết bị không đạt kiểm tra toàn vẹn (root/jailbreak/debug). Ứng dụng tạm ngừng để bảo vệ dữ liệu."),
        "integrity_blocked_exit": ("Exit", "Thoát"),
        
        "safe_boot_retry": ("Retry", "Thử lại"),
        "safe_boot_wipe_data": ("Recover (wipe data)", "Khôi phục dữ liệu (xóa)"),
        "bootstrap_init_failed_message": ("Failed to initialize data. Existing data may be corrupted.", "Không thể khởi tạo dữ liệu. Dữ liệu cũ có thể đã bị lỗi."),
        "debug_section_title": ("Debug", "Debug"),
        "debug_server_url_placeholder": ("Debug server URL", "Debug server URL"),
        "debug_send_test_event": ("Send test event", "Send test event"),
        
        "mark_as_taken": ("Mark as taken", "Đánh dấu đã uống"),
        "already_taken": ("Already taken", "Đã uống"),
        "already_skipped": ("Already skipped", "Đã bỏ qua"),
        "active": ("Active", "Đang active"),
        "show_details": ("Show details", "Hiện chi tiết"),
        "hide_details": ("Hide details", "Ẩn chi tiết"),
        "show_link_code": ("Show link code", "Hiện mã liên kết"),
        "hide_link_code": ("Hide link code", "Ẩn mã liên kết"),
        "notification_reliability_health": ("Reminder health", "Tình trạng lịch nhắc"),
        "notification_reliability_missing": ("Missing registered alarms", "Báo thức đã đăng ký bị thiếu"),
        "notification_reliability_stale": ("Stale schedule entries", "Mục lịch nhắc đã cũ"),
        "notification_reliability_mismatch": ("Schedule mismatches", "Lịch nhắc không khớp"),
        "notification_reliability_rebuild": ("Rebuild schedules", "Dựng lại lịch nhắc"),
        "notification_reliability_healthy": ("Healthy", "Ổn định"),
        "notification_reliability_degraded": ("Needs review", "Cần kiểm tra"),
        "notification_reliability_needs_repair": ("Repair recommended", "Nên sửa lịch nhắc"),
        "notification_reliability_inactive": ("Inactive", "Không hoạt động"),
        "coach_window_days_format": ("%d days", "%d ngày"),
        "coach_report_window": ("Report window", "Khoảng báo cáo"),
        "coach_report_window_format": ("Client report · %d days", "Báo cáo học viên · %d ngày"),
        "coach_report_total_format": ("%d%% completion · %d taken · %d skipped", "Hoàn thành %d%% · Đã uống %d · Bỏ qua %d"),
        "coach_trend_title": ("Adherence trend", "Xu hướng tuân thủ"),
        "coach_search_clients": ("Search clients", "Tìm học viên"),
        "coach_sort_title": ("Sort clients", "Sắp xếp học viên"),
        "coach_sort_attention": ("Check-in", "Cần hỏi lại"),
        "coach_sort_name": ("Name", "Tên"),
        "coach_sort_completion": ("Completion", "Hoàn thành"),
        "sync_health_unlinked": ("Not linked", "Chưa liên kết"),
        "sync_health_idle": ("Ready to sync", "Sẵn sàng đồng bộ"),
        "sync_health_healthy": ("Sync healthy", "Đồng bộ ổn định"),
        "sync_health_pending": ("Local changes pending", "Có thay đổi cục bộ đang chờ"),
        "sync_health_needs_key": ("Encryption key required", "Cần khóa mã hóa"),
        "sync_health_retryable": ("Temporary sync problem", "Lỗi đồng bộ tạm thời"),
        "sync_health_action_required": ("Sync needs attention", "Đồng bộ cần kiểm tra"),
        "sync_health_hint_none": ("No recovery action is required.", "Không cần thao tác khôi phục."),
        "sync_health_hint_sync_now": ("Retry safely; local data is kept.", "Có thể thử lại an toàn; dữ liệu cục bộ vẫn được giữ."),
        "sync_health_hint_import_key": ("Import the matching key below before retrying.", "Nhập đúng khóa bên dưới trước khi thử lại."),
        "sync_health_hint_check_link": ("Review the Link Code and sync configuration before retrying.", "Kiểm tra mã liên kết và cấu hình đồng bộ trước khi thử lại.")
    ]
    
    public func string(for key: String) -> String {
        guard let translation = dictionary[key] else { return key }
        return isVietnamese ? translation.vi : translation.en
    }
}

public extension String {
    var localized: String {
        LocalizationService.shared.string(for: self)
    }
}
