import SwiftUI

public struct LocalizationService: Sendable {
    public static let shared = LocalizationService()
    
    private init() {}
    
    private var isVietnamese: Bool {
        guard let preferredLanguage = Locale.preferredLanguages.first else { return false }
        return preferredLanguage.hasPrefix("vi")
    }
    
    private let dictionary: [String: (en: String, vi: String)] = [
        "tab_home": ("Home", "Trang chủ"),
        "tab_history": ("History", "Lịch sử"),
        "tab_settings": ("Settings", "Cài đặt"),
        "dashboard_title": ("Dashboard", "Dashboard"),
        "history_title": ("History", "Lịch sử"),
        "intake_frequency_last_7": ("Intake Frequency (Last 7 days)", "Tần suất uống (7 ngày qua)"),
        "insights_title": ("Insights", "Gợi ý (7/30 ngày)"),
        "insights_last_7": ("Last 7 days", "7 ngày"),
        "insights_last_30": ("Last 30 days", "30 ngày"),
        "insights_no_data": ("Not enough data.", "Chưa đủ dữ liệu."),
        "insights_completion_format": ("Completion: %d%%", "Hoàn thành: %d%%"),
        "insights_late_format": ("Late: %d", "Trễ: %d"),
        "insights_top_late_hour_format": ("Late hour: %1$@ (%2$d)", "Giờ hay trễ: %1$@ (%2$d)"),
        "insights_top_skipped_format": ("Top skipped: %1$@ (%2$d)", "Hay bỏ qua: %1$@ (%2$d)"),
        "insights_top_late_format": ("Top late: %1$@ (%2$d)", "Hay trễ: %1$@ (%2$d)"),
        "log_details": ("Log Details", "Chi tiết nhật ký"),
        "no_logs_yet": ("No logs yet.", "Chưa có nhật ký nào."),
        "today_intake_title": ("Today's Intake", "Cần uống hôm nay"),
        "no_intake_today": ("No intake scheduled for today.", "Không có lịch uống hôm nay."),
        "add_client_to_start": ("Add a Client to start.", "Thêm một học viên để bắt đầu."),
        "Add a Client to start.": ("Add a Client to start.", "Thêm một học viên để bắt đầu."),
        "resting_title": ("Resting", "Đang nghỉ"),
        "taken": ("Taken", "Đã uống"),
        "settings_title": ("Settings", "Cài đặt"),
        "client_management": ("Client Management", "Quản lý học viên"),
        "add_client": ("Add a Client", "Thêm học viên mới"),
        "edit_client": ("Edit Client", "Sửa học viên"),
        "add_supplement_title": ("Add Supplement", "Thêm chất mới"),
        "edit_supplement_title": ("Edit Supplement", "Chỉnh sửa"),
        "basic_info_title": ("Basic Info", "Thông tin cơ bản"),
        "schedule_cycle_title": ("Schedule & Cycle", "Lịch trình & Chu kỳ"),
        "name_hint": ("Name (e.g., Vitamin D3)", "Tên chất (VD: Vitamin D3)"),
        "dose_hint": ("Daily dose (e.g., 1000 IU)", "Liều lượng hàng ngày (VD: 1000 IU)"),
        "add_supplement_error_invalid_name": ("Name is required.", "Vui lòng nhập tên."),
        "add_supplement_error_invalid_time": ("Invalid intake time.", "Giờ uống không hợp lệ."),
        "add_supplement_error_invalid_cycle_days": ("Invalid cycle days.", "Ngày uống/nghỉ không hợp lệ."),
        "add_supplement_error_save_failed_format": ("Save failed: %@", "Lưu thất bại: %@"),
        "start_date": ("Start date", "Ngày bắt đầu"),
        "intake_time": ("Intake time", "Giờ uống"),
        "add_time": ("Add time", "Thêm giờ"),
        "notif_action_taken": ("Taken", "Đã uống"),
        "notif_action_skip": ("Skip", "Bỏ qua"),
        "repeat_weekly": ("Repeat by weekdays", "Lặp theo thứ"),
        "repeat_on_weekdays": ("Repeat on", "Lặp vào"),
        "repeat_every": ("Every (weeks)", "Cách mỗi (tuần)"),
        "every_x_weeks_format": ("Every %d week(s)", "Mỗi %d tuần"),
        "example_on_days": ("e.g., 14", "Ví dụ: 14"),
        "example_off_days": ("e.g., 7", "Ví dụ: 7"),
        "save": ("Save", "Lưu"),
        "cancel": ("Cancel", "Hủy"),
        "delete": ("Delete", "Xóa"),
        "edit": ("Edit", "Chỉnh sửa"),
        "appearance_title": ("Appearance", "Giao diện"),
        "appearance_light": ("Light", "Sáng"),
        "appearance_dark": ("Dark", "Tối"),
        "appearance_system": ("System", "Hệ thống"),
        "my_list_title": ("My List", "Danh sách của tôi"),
        "manage_stack": ("Manage Stack", "Quản lý Stack"),
        "no_supplements_yet": ("No supplements yet.", "Chưa có thực phẩm bổ sung."),
        "user_guide_title": ("User Guide", "Hướng dẫn sử dụng"),
        "settings_guide_1": ("Tap (+) to add supplements. The app auto-calculates On/Off cycles from the start date.", "Nhấn (+) để thêm chất. App tự động tính chu kỳ On/Off (uống/nghỉ) dựa trên ngày bắt đầu."),
        "settings_guide_2": ("Open Settings → Sync Center. On Host: (recommended) enable Cloud Encryption, then tap Host Data to create a Link Code. On Link: enter the code and tap Download. Enable Auto-Sync if you want realtime syncing.", "Vào Cài đặt → Sync Center. Thiết bị A (Host): (khuyến nghị) bật \"Mã hoá dữ liệu cloud\" rồi bấm \"Phát dữ liệu\" để tạo mã. Thiết bị B (Link): nhập mã và bấm \"Tải về\". Bật \"Tự động đồng bộ\" nếu muốn sync realtime."),
        "settings_guide_3": ("If encryption is enabled, copy Sync Key from Host and Import on other devices. After rotating the key, re-import the new key. Use the eye icon to hide the Link Code in public. Use Revoke to permanently delete cloud data when you no longer need syncing.", "Nếu bật mã hoá, Copy \"Sync key\" từ Host và Import trên thiết bị còn lại. Sau khi Rotate key thì phải import lại key mới. Nhấn biểu tượng \"Con mắt\" để ẩn mã ở nơi công cộng. Dùng \"Thu hồi\" để xoá vĩnh viễn dữ liệu Cloud khi không còn nhu cầu sync."),
        "settings_guide_4": ("Check Notification List to confirm the app sent schedules. Ensure Battery Optimization (Android) / Focus (iOS) isn’t blocking.", "Nếu lỡ mốc giờ, vào \"Kiểm tra danh sách\" để xem app đã đặt lệnh cho hệ điều hành chưa. Đảm bảo đã tắt \"Tối ưu hóa pin\" (Android) hoặc \"Không làm phiền\" (iOS)."),
        "about_title": ("About", "Giới thiệu"),
        "settings_about_body": ("OAK Healthy - Professional supplement tracker for Traders, Athletes, and Doctors monitoring patients.", "OAK Healthy - Trợ lý quản lý thực phẩm bổ sung chuyên nghiệp dành cho Trader, Vận Động Viên và cả Bác Sĩ theo dõi bệnh nhân."),
        "copyright_title": ("Copyright & Author", "Bản quyền & Tác giả"),
        "settings_app_name_label": ("OAK Healthy v1.0", "Tên app: OAK Healthy v1.0"),
        "settings_author_label": ("Mr. Phong (Personal Trader)", "Tác giả: Mr. Phong (Personal Trader)"),
        "settings_copyright_body": ("Copyright © 2026 OAK Healthy. All rights reserved.", "Copyright © 2026 OAK Healthy. Mọi bản quyền được bảo lưu."),
        "export_data": ("Export Data", "Xuất dữ liệu"),
        "import_data": ("Import Data", "Nhập dữ liệu"),
        "share_stack": ("Share Stack", "Chia sẻ danh sách"),
        "data_tools": ("Data", "Dữ liệu"),
        "error_title": ("Error", "Lỗi"),
        "ok": ("OK", "OK"),
        "back": ("Back", "Quay lại"),
        "onboarding_title": ("Setup", "Thiết lập"),
        "onboarding_next": ("Next", "Tiếp tục"),
        "onboarding_done": ("Done", "Xong"),
        "onboarding_open_settings": ("Open Settings", "Mở Cài đặt"),
        "onboarding_step_client_title": ("Choose a client", "Chọn học viên"),
        "onboarding_step_client_body": ("Select an existing client or create a new one to start tracking.", "Chọn học viên hiện có hoặc tạo mới để bắt đầu theo dõi."),
        "onboarding_step_notifications_title": ("Enable notifications", "Bật thông báo"),
        "onboarding_step_notifications_body": ("Enable notifications so reminders can work reliably.", "Bật thông báo để nhắc uống hoạt động ổn định."),
        "onboarding_notifications_denied": ("Notifications are denied. Enable them in Settings to receive reminders.", "Bạn đã tắt quyền thông báo. Hãy bật lại trong Cài đặt để nhận nhắc uống."),
        "onboarding_permission_status": ("Permission", "Quyền"),
        "onboarding_permission_granted": ("Granted", "Đã cho phép"),
        "onboarding_permission_denied": ("Denied", "Chưa cho phép"),
        "onboarding_permission_not_determined": ("Not asked", "Chưa hỏi"),
        "onboarding_send_test_notification": ("Send test notification", "Gửi thông báo test"),
        "onboarding_test_notification_body": ("Test notification from OAK Healthy.", "Thông báo test từ OAK Healthy."),
        "onboarding_test_sent_format": ("Sent: %@", "Đã gửi: %@"),
        "onboarding_test_ack_format": ("Opened: %@", "Đã mở: %@"),
        "onboarding_reschedule_now": ("Reschedule now", "Đặt lại lịch ngay"),
        "notification_diagnostics_title": ("Notification diagnostics", "Chẩn đoán thông báo"),
        "settings_clear_pending_notifications": ("Clear pending notifications", "Xoá lịch nhắc (pending)"),
        "onboarding_step_done_title": ("All set", "Hoàn tất"),
        "onboarding_step_done_body": ("You can change these settings anytime in Settings.", "Bạn có thể đổi các thiết lập này bất cứ lúc nào trong Cài đặt."),
        "import_failed": ("Import failed.", "Nhập dữ liệu thất bại."),
        "export_failed": ("Export failed.", "Xuất dữ liệu thất bại."),
        "invalid_json": ("Invalid JSON file.", "File JSON không hợp lệ."),
        "missing_active_client": ("Please select a client first.", "Vui lòng chọn học viên trước."),
        "client_name_label": ("Name", "Tên"),
        "supplement_advice_vitamin_d3": ("Take with a fat-containing meal for better absorption.", "Uống cùng bữa ăn có chất béo để hấp thụ tốt hơn."),
        "supplement_advice_ashwagandha": ("Supports stress reduction and sleep quality.", "Hỗ trợ giảm stress và cải thiện chất lượng giấc ngủ."),
        "supplement_advice_boron": ("Cycle it to support hormone optimization.", "Nên dùng theo chu kỳ để hỗ trợ tối ưu hormone."),
        "supplement_advice_magnesium": ("Supports muscles and nervous system. Take before sleep.", "Uống 30 phút trước khi đi ngủ."),
        "supplement_advice_caffeine": ("Boosts focus and energy for workouts and trading sessions. Take ~30 minutes pre-workout.", "Tăng tập trung và năng lượng trước khi tập hoặc giao dịch. Uống khoảng 30 phút trước khi tập."),
        "supplement_advice_omega_3": ("Take after a fatty meal for best absorption.", "Nên uống sau bữa ăn có chất béo để hấp thụ tốt nhất."),
        "supplement_advice_coq10": ("Supports cellular energy. Take after a meal.", "Hỗ trợ năng lượng tế bào. Nên uống sau bữa ăn."),
        "supplement_advice_creatine": ("Supports strength and performance. Take daily.", "Hỗ trợ sức mạnh và hiệu suất. Uống mỗi ngày để duy trì."),
        "supplement_advice_zinc": ("Avoid taking on an empty stomach.", "Tránh uống khi bụng đói."),
        "supplement_advice_nac": ("Take near bedtime if it suits you. Avoid taking too late if it disrupts sleep.", "Gợi ý: uống gần giờ đi ngủ (trước khi ngủ khoảng 30–60 phút). Nếu bạn nhạy cảm, tránh uống quá muộn."),
        "update_available_title": ("Update Available", "Có bản cập nhật mới"),
        "update_available_message_format": ("Update to get the latest features and security improvements (v%@).", "Hãy cập nhật để trải nghiệm những tính năng mới nhất và tăng cường bảo mật (v%@)."),
        "update_now": ("Update Now", "Cập nhật ngay"),
        "later": ("Later", "Để sau"),
        "update_description": ("Update Coach Mode, Liquid Glass UI, and data synchronization.", "Cập nhật tính năng Quản lý học viên (Coach Mode), tối ưu giao diện Liquid Glass và đồng bộ dữ liệu."),
        "dedication_text": ("With all dedication and research in the fitness & trading journey.", "Bằng cả tâm huyết và nghiên cứu trong hành trình gym & trading."),
        "factory_reset": ("Factory Reset", "Khôi phục cài đặt gốc"),
        "wipe_data_warning": ("This will permanently delete all clients and logs. Continue?", "Hành động này sẽ xóa toàn bộ dữ liệu học viên và nhật ký. Tiếp tục?"),
        "not_available": ("N/A", "N/A"),
        "dose_format": ("Dose: %@", "Liều lượng: %@"),
        "days_remaining_format": ("%d days left", "Còn %d ngày"),
        "cycle_status_on": ("In cycle", "Đang trong chu kỳ"),
        "cycle_status_off": ("In rest", "Đang trong kỳ nghỉ"),
        "dose_status_missed": ("Missed", "Quá hạn"),
        "dose_status_skipped": ("Skipped", "Bỏ qua"),
        "dose_status_planned": ("Planned", "Chưa uống"),
        "cycle_continuous": ("Continuous", "Uống liên tục"),
        "cycle_summary_format": ("%@, %d on / %d off", "%@, %d ngày uống / %d ngày nghỉ"),
        "cycle_label_day_format": ("Day %d/%d", "Ngày %d/%d"),
        "cycle_label_rest_format": ("Rest %d/%d", "Nghỉ %d/%d"),
        "continuous": ("Continuous", "Uống liên tục"),
        "on_days": ("On Days", "Số ngày uống"),
        "off_days": ("Off Days", "Số ngày nghỉ"),
        "duration": ("Duration", "Tổng thời hạn"),
        "months": ("Months", "Tháng"),
        "unlimited": ("Unlimited", "Vô thời hạn"),
        "suggested_format": ("Suggested: %@", "Gợi ý: %@"),
        "notification_title": ("Time to take it! 🌿", "Đến giờ uống rồi! 🌿"),
        "notification_body_format": ("You need to take %1$@ - Dose: %2$@. Wishing you a productive work/trading session!", "Bạn cần nạp %1$@ - Liều lượng: %2$@. Chúc bạn một phiên giao dịch/làm việc hiệu quả!"),
        "chart_axis_day": ("Day", "Ngày"),
        "chart_axis_count": ("Count", "Số lần"),
        
        "sync_center_title": ("Sync Center", "Sync Center"),
        "sync_center_notice_title": ("Notice", "Thông báo"),
        "sync_center_auto_sync": ("Auto-Sync", "Tự động đồng bộ"),
        "sync_center_onboarding_header": ("Onboarding", "Onboarding"),
        "sync_center_onboarding_host_1": ("1) Enable encryption for security (recommended).", "1) Bật Mã hoá nếu muốn bảo mật (khuyến nghị)."),
        "sync_center_onboarding_host_2": ("2) Tap Host to create a link code.", "2) Bấm Phát dữ liệu để tạo mã liên kết."),
        "sync_center_onboarding_host_3": ("3) Copy the code to device B (Link tab).", "3) Copy mã và gửi sang thiết bị B (tab Link)."),
        "sync_center_onboarding_link_1": ("1) Enter the code from device A.", "1) Nhập mã liên kết từ thiết bị A."),
        "sync_center_onboarding_link_2": ("2) Tap Download to pull + merge data.", "2) Bấm Tải về để pull + merge dữ liệu."),
        "sync_center_onboarding_link_3": ("3) If encryption is enabled, import the key to decrypt cloud data.", "3) Nếu đang bật mã hoá, import key tương ứng để đọc dữ liệu cloud."),
        
        "sync_center_status_header": ("Status", "Trạng thái"),
        "sync_center_last_sync_format": ("Last sync: %@", "Lần sync gần nhất: %@"),
        "sync_center_last_attempt_format": ("Last attempt: %@", "Lần thử gần nhất: %@"),
        "sync_center_no_sync_yet": ("No sync yet.", "Chưa có sync lần nào"),
        "sync_center_phase_format": ("Phase: %@", "Trạng thái: %@"),
        "sync_center_chip_pull": ("Pull", "Pull"),
        "sync_center_chip_merge": ("Merge", "Merge"),
        "sync_center_chip_push": ("Push", "Push"),
        "sync_center_pending_changes": ("Local changes pending upload.", "Có thay đổi cục bộ chưa upload"),
        "sync_center_no_pending_changes": ("No local pending changes.", "Không có thay đổi cục bộ"),
        "sync_center_conflict_retry_format": ("Conflict retry: %d/1", "Conflict retry: %d/1"),
        "sync_center_bytes_format": ("Download: %@ • Upload: %@", "Download: %@ • Upload: %@"),
        "sync_center_timings_format": ("Pull %dms • Merge %dms • Push %dms • Total %dms", "Pull %dms • Merge %dms • Push %dms • Total %dms"),
        "sync_center_last_error_format": ("Last error: %@", "Lỗi lần trước: %@"),
        "sync_center_hint_missing_key": ("Hint: missing sync key. Copy the key from Host and import it in Security.", "Gợi ý: có thể thiếu sync key. Hãy copy key từ thiết bị Host và Import key trong mục Bảo mật."),
        "sync_center_sync_now": ("Sync now", "Sync ngay"),
        "sync_center_no_link_code": ("No link code yet. Use Host to create one, or Link to enter a code.", "Chưa có mã liên kết. Vào tab Host để phát, hoặc tab Link để nhập mã."),
        
        "sync_center_tab_host": ("Host", "Host"),
        "sync_center_tab_link": ("Link", "Link"),
        "sync_center_device_header": ("Device", "Thiết bị"),
        
        "sync_center_host_action": ("Host", "Phát dữ liệu"),
        "sync_center_rehost_confirm": ("Re-host? Current code will be revoked and a new one will be created.", "Phát dữ liệu lại? Mã hiện tại sẽ bị thu hồi và tạo mã mới."),
        "sync_center_rehost_confirm_action": ("Create new code", "Tạo mã mới"),
        "sync_center_your_link_code": ("Your link code:", "Mã liên kết của bạn:"),
        "sync_center_revoke_action": ("Revoke code", "Thu hồi mã"),
        "sync_center_revoke_confirm": ("Are you sure you want to revoke the code? Other devices will no longer be able to sync.", "Bạn chắc chắn muốn thu hồi mã? Thiết bị khác sẽ không còn sync được với mã hiện tại."),
        "sync_center_host_hint": ("Create a link code so another device can enter it in the Link tab.", "Tạo mã liên kết để thiết bị khác nhập vào tab Link."),
        
        "sync_center_link_code_placeholder": ("Enter link code", "Nhập mã liên kết"),
        "sync_center_download_action": ("Download", "Tải về"),
        
        "sync_center_security_header": ("Security", "Bảo mật"),
        "sync_center_encryption_toggle": ("Cloud encryption", "Mã hoá dữ liệu cloud"),
        "sync_center_disable_encryption_confirm": ("Disable encryption? Data will be uploaded as plaintext JSON.", "Tắt mã hoá? Dữ liệu sẽ upload dạng plaintext JSON."),
        "sync_center_disable_encryption_action": ("Disable encryption", "Tắt mã hoá"),
        "sync_center_keep_encryption_action": ("Keep encryption", "Giữ mã hoá"),
        "sync_center_export_key_label": ("Sync key (copy to other device):", "Sync key (copy sang thiết bị khác):"),
        "sync_center_rotate_key_action": ("Rotate key", "Rotate key"),
        "sync_center_rotate_key_confirm": ("Rotate key? Other devices must import the new key to decrypt new uploads.", "Rotate key? Thiết bị khác cần import key mới để đọc dữ liệu upload sau khi rotate."),
        "sync_center_refresh_key_action": ("Refresh key", "Refresh key"),
        "sync_center_import_key_placeholder": ("Enter keyId:base64", "Nhập keyId:base64"),
        "sync_center_import_key_action": ("Import key", "Import key"),
        "sync_center_encryption_off_hint": ("When disabled, data is uploaded as plaintext JSON.", "Khi tắt, dữ liệu sẽ upload dạng plaintext JSON."),
        
        "sync_center_import_key_confirm_invalid": ("Import key? Format: keyId:base64", "Import key? (format keyId:base64)"),
        "sync_center_import_key_confirm_same_current_format": ("Import key? KeyId matches current key (%@).", "Import key? KeyId trùng current key (%@)."),
        "sync_center_import_key_confirm_same_previous_format": ("Import key? KeyId matches previous key (%@).", "Import key? KeyId trùng previous key (%@)."),
        "sync_center_import_key_confirm_format": ("Import key? KeyId: %@", "Import key? KeyId: %@"),
        
        "sync_center_logs_header": ("Logs", "Log"),
        "sync_center_logs_hint": ("Logs will appear when you host/link and run sync.", "Log sẽ xuất hiện khi bạn host/link và thực hiện sync."),
        "sync_center_logs_search_placeholder": ("Search logs", "Tìm trong log"),
        "sync_center_logs_phase": ("Phase", "Phase"),
        "sync_center_logs_phase_all": ("All", "All"),
        "sync_log_phase_host": ("Host", "Host"),
        "sync_log_phase_sync": ("Sync", "Sync"),
        "sync_log_phase_conflict": ("Conflict", "Conflict"),
        "sync_log_phase_done": ("Done", "Xong"),
        "sync_log_phase_error": ("Error", "Lỗi"),
        "sync_center_logs_export": ("Export log", "Export log"),
        "sync_center_logs_clear": ("Clear log", "Clear log"),
        "sync_center_clear_log_confirm": ("Clear sync logs? This only clears logs on this device.", "Xoá log sync? Hành động này chỉ xoá log trên thiết bị hiện tại."),
        "sync_center_clear_log_action": ("Clear log", "Xoá log"),
        "sync_center_no_logs": ("No logs yet.", "Chưa có log."),
        
        "sync_center_toast_missing_client": ("Missing active client.", "Thiếu client đang chọn."),
        "sync_center_toast_missing_link_code": ("Please enter a link code.", "Vui lòng nhập mã liên kết."),
        "sync_center_toast_host_success": ("Hosted successfully!", "Phát dữ liệu thành công!"),
        "sync_center_toast_host_failed_format": ("Host failed: %@", "Phát dữ liệu thất bại: %@"),
        "sync_center_toast_revoke_done": ("Code revoked.", "Đã vô hiệu hóa mã."),
        "sync_center_toast_revoke_failed_format": ("Revoke failed: %@", "Thu hồi mã thất bại: %@"),
        "sync_center_toast_sync_success": ("Sync completed.", "Đã đồng bộ thành công."),
        "sync_center_toast_sync_failed_format": ("Sync failed: %@", "Sync thất bại: %@"),
        "sync_center_toast_encryption_on": ("Encryption enabled.", "Đã bật mã hoá."),
        "sync_center_toast_encryption_off": ("Encryption disabled.", "Đã tắt mã hoá."),
        "sync_center_toast_encryption_failed_format": ("Encryption failed: %@", "Mã hoá thất bại: %@"),
        "sync_center_toast_rotate_done": ("Key rotated.", "Đã rotate key."),
        "sync_center_toast_rotate_failed_format": ("Rotate failed: %@", "Rotate key thất bại: %@"),
        "sync_center_toast_import_key_done": ("Key imported.", "Đã import key."),
        "sync_center_toast_import_key_failed_format": ("Import failed: %@", "Import key thất bại: %@"),
        "sync_center_toast_code_copied": ("Copied to clipboard.", "Đã sao chép mã vào clipboard."),
        "sync_center_toast_log_cleared": ("Logs cleared.", "Đã xoá log."),
        "sync_center_stack_id_label_format": ("Stack: %@", "Stack: %@"),
        "sync_center_history_id_label_format": ("History: %@", "History: %@"),
        
        "sync_phase_idle": ("Idle", "Idle"),
        "sync_phase_pulling": ("Pulling", "Đang pull"),
        "sync_phase_merging": ("Merging", "Đang merge"),
        "sync_phase_pushing": ("Pushing", "Đang push"),
        "sync_phase_retrying_conflict": ("Retrying (conflict)", "Đang retry (conflict)"),
        "sync_phase_done": ("Done", "Done"),
        "sync_phase_error": ("Error", "Error"),
        
        "import_notice_title": ("Import Notice", "Thông báo Nhập dữ liệu"),
        "notification_permission_toggle": ("Allow notifications", "Cho phép gửi thông báo"),
        "notification_reschedule_now": ("Reschedule notifications now", "Đặt lịch lại thông báo"),
        "notification_clear_pending": ("Clear pending notifications", "Xoá thông báo đang chờ"),
        "settings_notifications_title": ("Notifications", "Thông báo"),
        "notification_pending_format": ("Pending: %d", "Đang chờ: %d"),
        "notification_clear_pending_confirm_title": ("Clear pending notifications?", "Xoá thông báo đang chờ?"),
        "notification_clear_pending_confirm_message": ("This will remove all scheduled reminders on this device. Continue?", "Hành động này sẽ xoá toàn bộ lịch nhắc trên thiết bị này. Tiếp tục?"),
        "notification_debug_title": ("Notification List", "Danh sách thông báo"),
        "notification_debug_link": ("Check notification list", "Kiểm tra danh sách thông báo"),
        "notification_debug_empty": ("No schedules yet. Enable “Allow notifications” to activate.", "Chưa có mốc giờ nào. Vui lòng bật 'Cho phép gửi thông báo' để kích hoạt."),
        "notification_debug_dose_format": ("Dose: %@", "Liều lượng: %@"),
        "backup_last_export_format": ("Last export: %@", "Xuất lần cuối: %@"),
        "backup_last_import_format": ("Last import: %@", "Nhập lần cuối: %@"),
        "backup_json_placeholder": ("Paste backup JSON here…", "Dán JSON backup vào đây…"),
        "backup_paste_from_clipboard": ("Paste from clipboard", "Dán từ clipboard"),
        "backup_preview_action": ("Preview", "Xem trước"),
        "backup_preview_title": ("Preview", "Xem trước"),
        "backup_preview_schema_label": ("Schema", "Schema"),
        "backup_preview_updated_label": ("Updated", "Cập nhật"),
        "backup_preview_device_label": ("Device", "Thiết bị"),
        "backup_preview_stack_label": ("Stack", "Stack"),
        "backup_preview_history_label": ("History", "Lịch sử"),
        
        "multi_device_sync_header": ("Multi-device Sync", "Đồng bộ đa thiết bị"),
        
        "history_today": ("Today", "Hôm nay"),
        "history_yesterday": ("Yesterday", "Hôm qua"),
        "filter_all": ("All", "Tất cả"),
        "history_search_placeholder": ("Search supplements", "Tìm theo tên chất"),
        
        "home_confirm_intake_title": ("Confirm intake?", "Xác nhận uống?"),
        "home_confirm_intake_action": ("Taken", "Đã uống"),
        "home_confirm_intake_message": ("This action will be recorded in History and cannot be undone.", "Hành động này sẽ được ghi vào Lịch sử và không thể hoàn tác."),
        "home_streak_format": ("Streak: %d", "Chuỗi: %d"),
        "home_due_soon": ("Due soon", "Sắp tới"),
        "home_almost_missed": ("Almost missed", "Sắp trễ"),
        
        "user_guide_section_1_title": ("Section 1: Setup Stack", "Mục 1: Thiết lập Stack"),
        "user_guide_section_2_title": ("Section 2: Multi-device Sync", "Mục 2: Đồng bộ đa thiết bị"),
        "user_guide_section_3_title": ("Section 3: Maximum Security", "Mục 3: Bảo mật tối cao"),
        "user_guide_section_4_title": ("Section 4: Notification Diagnostics", "Mục 4: Chẩn đoán thông báo"),
        
        "app_name": ("OAK Healthy", "OAK Healthy"),
        "preview_unavailable": ("Preview unavailable", "Không thể hiển thị preview"),
        "imported_client_default_name": ("Imported Client", "Học viên đã nhập"),
        
        "safe_mode_title": ("Safe Mode", "Chế độ an toàn"),
        "safe_mode_header": ("Safe Mode", "Chế độ an toàn"),
        "safe_mode_apply_button": ("Apply downloaded data", "Áp dụng dữ liệu đã tải"),
        "safe_mode_discard_button": ("Discard downloaded data", "Hủy dữ liệu đã tải"),
        "safe_mode_auto_sync_toggle": ("Auto-Sync", "Tự động đồng bộ"),
        "safe_mode_exit_button": ("Exit Safe Mode", "Thoát chế độ an toàn"),
        "safe_mode_detected_message": ("Downloaded data detected. Apply it here to prevent crashes on startup.", "Đã phát hiện dữ liệu đã tải. Hãy áp dụng từ đây để tránh văng app lúc khởi động."),
        "safe_mode_apply_success_message": ("Data applied. Exit Safe Mode to continue using the app.", "Áp dụng dữ liệu thành công. Hãy thoát chế độ an toàn để sử dụng app."),
        "safe_mode_apply_failed_format": ("Apply failed: %@", "Áp dụng dữ liệu thất bại: %@"),
        
        "safe_boot_retry": ("Retry", "Thử lại"),
        "safe_boot_wipe_data": ("Recover (wipe data)", "Khôi phục dữ liệu (xóa)"),
        "bootstrap_init_failed_message": ("Failed to initialize data. Existing data may be corrupted.", "Không thể khởi tạo dữ liệu. Dữ liệu cũ có thể đã bị lỗi."),
        "debug_section_title": ("Debug", "Debug"),
        "debug_server_url_placeholder": ("Debug server URL", "Debug server URL"),
        "debug_send_test_event": ("Send test event", "Send test event")
    ]
    
    public func string(for key: String) -> String {
        guard let translation = dictionary[key] else { return key }
        return isVietnamese ? translation.vi : translation.en
    }
}

public extension String {
    var localized: String {
        LocalizationService.shared.string(for: self)
    }
}
