default_platform(:ios)

platform :ios do
  desc "Build and Archive the iOS App"
  lane :build do
    gym(
      project: "OAKHealthy.xcodeproj",
      scheme: "OAKHealthy",
      configuration: "Release",
      skip_codesigning: true,
      skip_package_ipa: true,
      skip_package_pkg: true,
      clean: true,
      destination: "generic/platform=iOS",
      archive_path: "./build/OAKHealthy.xcarchive"
    )
  end
end
